### ISSUE TITLE
Missing pre- and post remove steps

### ISSUE THREAD

**Issue by volker-raschek** [Richterrettich/rpm-builder#8]
Currently the rpm-builder provide only support for pre_installation and post_installation by `--post-install-script ` and `--pre-install-script`.

Please add additional flags for pre_update, post_update, pre_remove and post_remove.

Volker

**Comment by Richterrettich** [comment]
RPM does not have specific hooks for upgrading. It seems that it works like this during upgrade:

https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#ordering

In short: install and removal hooks will be used during updates.

It is true that there are currently no parameters for pre and post remove.
